<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6LJCPTQ" failures="4" tests="5" name="Maven_testNG_POM_Test" time="48.682" errors="0" timestamp="2021-10-14T13:47:02 EDT">
  <testcase classname="testCases.Test_loginPage" name="TC001_login" time="10.957">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.Test_loginPage.validate_Login(Test_loginPage.java:68)
at testCases.Test_loginPage.TC001_login(Test_loginPage.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC001_login -->
  <testcase classname="testCases.Test_loginPage" name="TC003_DDTlogin" time="12.205"/>
  <testcase classname="testCases.Test_loginPage" name="TC003_DDTlogin" time="10.555">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.Test_loginPage.validate_Login(Test_loginPage.java:68)
at testCases.Test_loginPage.TC003_DDTlogin(Test_loginPage.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC003_DDTlogin -->
  <testcase classname="testCases.Test_loginPage" name="TC003_DDTlogin" time="10.996">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.Test_loginPage.validate_Login(Test_loginPage.java:68)
at testCases.Test_loginPage.TC003_DDTlogin(Test_loginPage.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC003_DDTlogin -->
  <testcase classname="testCases.Test_loginPage" name="TC003_DDTlogin" time="10.691">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.Test_loginPage.validate_Login(Test_loginPage.java:68)
at testCases.Test_loginPage.TC003_DDTlogin(Test_loginPage.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC003_DDTlogin -->
</testsuite> <!-- Maven_testNG_POM_Test -->
